version: '3.8'
services:
  #wordpress
  wordpress:
    container_name: wordpress
    build:
      context: ./docker/images/wordpress_with_test_plugin/
      args:
        - WP_VERSION=${WORDPRESS_VERSION:-6.4.1}
        - PHP_VERSION=${PHP_VERSION:-8.2}
        - WEBSERVER_VERSION=${WEBSERVER_VERSION:-apache}
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-mariadb}
      - WORDPRESS_DB_USER=${DATABASE_USER}
      - WORDPRESS_DB_NAME=${DATABASE_NAME}
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_user_password
      - WORDPRESS_TABLE_PREFIX=${DATABASE_TABLE_PREFIX:-wp_}
      - WORDPRESS_LOCALE=${WORDPRESS_LOCALE:-en_US}
      - WORDPRESS_WEBSITE_TITLE=${WORDPRESS_WEBSITE_TITLE:-Spin8 Test}
      - WORDPRESS_WEBSITE_URL=${WORDPRESS_WEBSITE_URL:-http://localhost}
      - WORDPRESS_WEBSITE_URL_WITHOUT_HTTP=${WORDPRESS_WEBSITE_URL_WITHOUT_HTTP:-localhost}
      - WORDPRESS_WEBSITE_POST_URL_STRUCTURE=${WORDPRESS_WEBSITE_POST_URL_STRUCTURE:-/%postname%/}
      - WORDPRESS_ADMIN_USER=${WORDPRESS_ADMIN_USER:-spin8}
      - WORDPRESS_ADMIN_PASSWORD=${WORDPRESS_ADMIN_PASSWORD:-spin8}
      - WORDPRESS_ADMIN_EMAIL=${WORDPRESS_ADMIN_EMAIL:-test@spin8.test}
      - TEST_PLUGIN_FOLDER=${TEST_PLUGIN_FOLDER:-spin8-test}
    ports:
      - ${WEBSERVER_PORT:-80}:80
    restart: always
    depends_on:
      - mariadb
    secrets:
      - db_user_password
    volumes:
      - wp_data:/var/www/html
      - ./src:/var/www/html/wp-content/plugins/${TEST_PLUGIN_FOLDER}/vendor/spin8/framewrok/src
      - ./composer.json:/var/www/html/wp-content/plugins/${TEST_PLUGIN_FOLDER}/vendor/spin8/framewrok/composer.json
      - ./composer.lock:/var/www/html/wp-content/plugins/${TEST_PLUGIN_FOLDER}/vendor/spin8/framewrok/composer.lock
  #mariadb
  mariadb:
    container_name: mariadb
    image: mariadb:${MARIADB_VERSION:-latest}
    ports:
      - ${DATABASE_PORT:-3306}:3306
    restart: always
    environment:
      - MARIADB_DATABASE=${DATABASE_NAME:-wp_spin8}
      - MARIADB_USER=${DATABASE_USER:-spin8}
      - MARIADB_PASSWORD_FILE=/run/secrets/db_user_password
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=''
      - MARIADB_ROOT_HOST=localhost
    secrets:
      - db_user_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
  wp_data:
secrets:
  db_user_password:
    file: ./docker/secrets/db_user_password.secret.txt
  db_root_password:
    file: ./docker/secrets/db_root_password.secret.txt
